### ISSUE TITLE
[BUG] Broken on SDDM, constant "Login failed" loop and flicker

### ISSUE THREAD

**Issue by qoijjj** [34N0/pam-authramp#48]
## Steps to reproduce:

Use authramp with SDDM / kinoite
enter incorrect passwords until lockout

## Expected behavior:

on lockout, a timer should be displayed

## Actual behavior: 

constant "login failed" loop.

Please confirm that you can repro.

**Comment by 34N0** [comment]
Hmm this means that SDDM renders the PAM conversation different than my test cases. I will try to reproduce this right now.

**Comment by qoijjj** [comment]
@34N0 sounds good, let me know if you can't and I can record the behavior.

**Comment by 34N0** [comment]
hmm. i just rebased one vm to secureblue kionite staging and i cannot log in at all. is this your behaviour?

I wonder if the problem is with authramp or the secureblue implementation. I will try to figure this out now.

**Comment by qoijjj** [comment]
> hmm. i just rebased one vm to secureblue kionite staging and i cannot log in at all. is this your behaviour?

No, I'm not seeing that behavior. I'm able to login. If I send 7 incorrect passwords though, I get a "login failed" loop and flicker for around 30 seconds.

**Comment by 34N0** [comment]
hmm ok so this is definitely related to the PAM conversation then. I will try to repro further.

**Comment by 34N0** [comment]
repro confirmed

**Comment by 34N0** [comment]
#57
