### ISSUE TITLE
On Plasma, the password prompt still works even during lock, and doesn't accept valid passwords

### ISSUE THREAD

**Issue by qoijjj** [34N0/pam-authramp#67]
Instead of Authentication failed, it now just lets me continuously enter passwords even after using the free tries. The only difference is after the free tries are used, a valid password no longer works.

Expected behavior:

During lock, passwords should not be able to be entered, and the text should tell the user they are locked out

Actual behavior:

During lock, passwords are still able to be entered, and there is no indication whatsoever that the system is locked.

Steps to reproduce:

Rebase to a secureblue `kinoite` vm with the `br-staging-39` tag.

**Comment by 34N0** [comment]
Thank you, I'll test this later today. If this is only regarding the user experience, have you ever tested the user experience with `pam_faillock` in the stable secureblue build? You can edit the settings in `/etc/security/faillock.conf`. The experience might be equally bad and then its an SDDM issue!

**Comment by qoijjj** [comment]
@34N0 There's something else at play here. Either SDDM or the existing secureblue config is broken:

```
# Deny access if the number of consecutive authentication failures
# for this user during the recent interval exceeds n tries.
# The default is 3.
deny = 3
#
# The length of the interval during which the consecutive
# authentication failures must happen for the user account
# lock out is <replaceable>n</replaceable> seconds.
# The default is 900 (15 minutes).
# fail_interval = 900
#
# The access will be re-enabled after n seconds after the lock out.
# The value 0 has the same meaning as value `never` - the access
# will not be re-enabled without resetting the faillock
# entries by the `faillock` command.
# The default is 600 (10 minutes).
unlock_time = 300
#
```

With this config and with pam_faillock, I'm never locked out at all. I can enter a valid password afterwards and I'm allowed in.

**Comment by 34N0** [comment]
> @34N0 There's something else at play here. Either SDDM or the existing secureblue config is broken:
> 
> ```
> # Deny access if the number of consecutive authentication failures
> # for this user during the recent interval exceeds n tries.
> # The default is 3.
> deny = 3
> #
> # The length of the interval during which the consecutive
> # authentication failures must happen for the user account
> # lock out is <replaceable>n</replaceable> seconds.
> # The default is 900 (15 minutes).
> # fail_interval = 900
> #
> # The access will be re-enabled after n seconds after the lock out.
> # The value 0 has the same meaning as value `never` - the access
> # will not be re-enabled without resetting the faillock
> # entries by the `faillock` command.
> # The default is 600 (10 minutes).
> unlock_time = 300
> #
> ```
> 
> With this config and with pam_faillock, I'm never locked out at all. I can enter a valid password afterwards and I'm allowed in.

I am unable to reproduce this. I am successfully getting locked out by faillock. But the user experience is equally bad with SDDM repeating "Authentication failed" and never informing the user of a lockout.

**Comment by 34N0** [comment]
In my testing there isn't currently any difference in user experience than the official pam_faillock module on SDDM

**Comment by 34N0** [comment]
> But if it locks out the user forever its a serious bug which evaded testing somehow!

This is was not an issue in my testing

**Comment by qoijjj** [comment]
Since we're seeing different behavior, let me do more testing. Also, is there already an SDDM bug created? I would create one but I feel like you have a better understanding of the interaction between pam and DMs in order to capture that in the report :smile:

**Comment by 34N0** [comment]
| image                    | tag     | dm      | pam          | lockout mechanism      | message                                                       |
|--------------------------|---------|---------|--------------|------------------------|---------------------------------------------------------------|
| Kionite-main-hardened    | latest  | SDDM    | pam_faillock | expected functionality | “Authentication failed”                                       |
| Kionite-main-hardened    | staging | SDDM    | pam_authramp | expected functionality | “Authentication failed”                                       |
| silverblue-main-hardened | latest  | GDM     | pam_faillock | expected functionality | “Sorry password authentication didn’t work, please try again” |
| silverblue-main-hardened | staging | GDM     | pam_authramp | expected functionality | “Account locked, unlocking in 9 seconds”                      |
| Cinnamon-main-hardened   | latest  | LightDM | pam_faillock | unable to login        | “Failed to start session”                                     |
| Cinnamon-main-hardened   | latest  | LightDM | pam_faillock | unable to login        | “Failed to start session”                                     |

Those are my testing results for reference. I rebased to each image from a fresh silverblue vm.

**Comment by 34N0** [comment]
> Since we're seeing different behavior, let me do more testing. Also, is there already an SDDM bug created? I would create one but I feel like you have a better understanding of the interaction between pam and DMs in order to capture that in the report 😄

Yes i'll create the BUG report myself :smile:

**Comment by 34N0** [comment]
Apparently this is a related open issue since 2017. There was a patch rejected a few years ago too which never got reopened. I might take my own shot at this in the near future.  https://github.com/sddm/sddm/issues/782

**Comment by 34N0** [comment]
> @34N0 Yikes. That makes me consider replacing SDDM with GDM for all of secureblue including the kinoite images.

This might be the way to go for now. But from a raw security perspective there isn't a downside to not showing the messages produces by either faillock or authramp. in faillock there is even the `silent` setting as a security feature which disables user messages. It's just really bad UX.

**Comment by 34N0** [comment]
The SDDM development seems to have different priorities, since there are some pull requests open for over five years. https://github.com/sddm/sddm/pull/776 is actually relevant for this issue but needs rebasing and renewed patches. There is also enough discussions about this in the SDDM repository.

**Comment by qoijjj** [comment]
@34N0 SDDM had a development gap for years. It's still in the process of being folded in to KDE, so once that completes, it might be worth asking KDE if they'd consider this change.
