### ISSUE TITLE
Key bypass

### ISSUE THREAD

**Issue by kohlrak** [34N0/pam-authramp#72]
I'm surprised no one came up with this before you did, but as I was planning on using PAM authentication for my website, and kinda already started (via SMTP), the idea of how to throttle brute force attempts has become a priority of mine, so i stumbled on your project yesterday.

Part of me, however, does see why this wasn't created before: what if someone tries to lock down a system and prevent an administrator from getting in via SSH by locking down all known user accounts (you acknowledge this for root)? I was wondering if, perhaps, there were some way to have it skip this module on public key authentication. This would effectively prevent that very idea. Bonus if you can get it to work with a way to bypass locally with some sort of command line option (so people can unlock their accounts) (odds are, most people using this are more afraid of external brute force attempts, not local users trying to break in).

I'd mark this as a feature request, myself, but I don't use github's issue reporting often enough to know how to do that.

**Comment by 34N0** [comment]
Hey, thank you for your input!

The very nature of PAM allows for different authentication services, which are sequential stacks of different modules.

I agree with you thath using this module as part of SSH authentication opens up a DOS vulnerability. Also you could setup your authentication services in a way that this module is not relevant for key authentication.

I think the reason why no one came up with this before is that linux security is mainly focussed on central managed domains, i.e. companies. The open source movement for security in private linux devices is quite young! :-)

**Comment by kohlrak** [comment]
> Hey, thank you for your input!
> 
> The very nature of PAM allows for different authentication services, which are sequential stacks of different modules.
> 
> I agree with you thath using this module as part of SSH authentication opens up a DOS vulnerability. Also you could setup your authentication services in a way that this module is not relevant for key authentication.

Well, it's not just SSH that's DoS vulnerable with this, but SMTP and IMAP as well as any other services. I'm considering your module due to the fact i want to use PAM for logins for my PHP code as well. SSH in particular, using public key authentication, would be a way to bypass this issue, except for the fact that PAM is still used by SSHD after public key login.

> 
> I think the reason why no one came up with this before is that linux security is mainly focussed on central managed domains, i.e. companies. The open source movement for security in private linux devices is quite young! :-)
> 
> For SSH exposed devices faillock might be the better protection anyways since one could always unlock the accounts via logging in with an admin account physically (or through a management console).
> 
> I'll leave this issue open for now. I am happy to discuss the design of this module further! :-)

Haven't heard of faillock until now, but it presents the exact same issue, unfortunately. The question is how to bypass a system where the admin accounts (other than root, which you can't access via ssh if your SSHD has security in mind) have been locked down? What i'm proposing is some way to detect public key auth via SSH (which, like i said, still uses PAM for public key authentication) so the user can unlock their own account.

I haven't actually tried your module yet, but i imagine it'd block SSH login via public key if, say, my account got locked from failed SMTP attempts. If there were a way SSHD could bypass this, then public key login would make this infinitely more valuable.

It turns out, faillock is enabled by default on my system, and I had no idea. It's also close enough to what i need, so i will stick with it. However, noting that public-key-authentication bypasses and resets it is useful and important, especially if you use PAM for other things.
