### ISSUE TITLE
add COPR builds for F40 and rawhide

### ISSUE THREAD

**Issue by boredsquirrel** [34N0/pam-authramp#76]
hey, it would be great to install the module on the latest Fedora release. And enabling rawhide with rebuilds on every git change may detect breakages in the next release early, and allow testing.

cheers!

**Comment by 34N0** [comment]
Hey thanks for your inputs, i will look at them if i find the time during the weekend! :-)

**Comment by 34N0** [comment]
i will release 1.0 this week with updated copr builds.

**Comment by 34N0** [comment]
leaving open until release

**Comment by 34N0** [comment]
https://copr.fedorainfracloud.org/coprs/34n0s/pam-authramp/
