### ISSUE TITLE
[BUG] Countdown clock text is inaccurate

### ISSUE THREAD

**Issue by qoijjj** [34N0/pam-authramp#79]
After triggering the lockout mechanism and the 30 second countdown, each second on the countdown takes about 1.5-2 seconds, clearing once it hits around 13 seconds remaining.

I used a stopwatch to time it, and the locking mechanism is accurate, it locks for 30 seconds. Just the countdown text itself is inaccurate.

**Comment by qoijjj** [comment]
I wonder if this is caused by lag in invoking conv.send()?

**Comment by 34N0** [comment]
I've noticed this before. I think it is a latency issue. One possible fix could be to only send a message every two seconds to get a more accurate remaining time. what do you think?

**Comment by 34N0** [comment]
> I wonder if this is caused by lag in pam invoking conv.send()?
> 
> However I don't recall this on earlier versions of pam-authramp
> 

hmm i'll test it with [pamtester](https://pamtester.sourceforge.net/). If there is the same issue, then it must lie with the authramp implementation.

**Comment by qoijjj** [comment]
thanks, and FYI this is on any secureblue silverblue image with tag br-staging-40

**Comment by 34N0** [comment]
This is OS or display manager latency. When using pamtester the 30s are actually 30s. Tested this with a stoppwatch. In theory displaying the message every 2nd second should help with the accuracy.

**Comment by 34N0** [comment]
16fd9f8

**Comment by qoijjj** [comment]
@34N0 That makes sense. Making this configurable could be an easy fix.

Or also, what about just displaying the timestamp when the user will be able to try again?

Something like `Locked until 2024-07-15 03:35:00 PM`

**Comment by qoijjj** [comment]
> [16fd9f8](https://github.com/34N0/pam-authramp/commit/16fd9f8bceffed1d8018f33046c19942e119283e)

That works too :)

Thanks

**Comment by 34N0** [comment]
lazy fix for now. but i am open for something simpler like the timestamp idea!

**Comment by qoijjj** [comment]
> Something like `Locked until 2024-07-15 03:35:00 PM`

I wonder though, do you think this is an option on SDDM or LightDM? or would it still not work?

**Comment by 34N0** [comment]
I think it wouldn't change the experience a lot on LightDM since it allways displays the latest countdown message but doesn't count lower automatically. SDDM does not display any PAM messages. It does not support it.

**Comment by qoijjj** [comment]
I see, makes sense

**Comment by qoijjj** [comment]
the countdown is much more accurate now!

there's still a little bit of drift, but it's roughly correct. Making this configurable or the timestamp I mentioned would be good nice-to-have features to make the experience even better, but overall it's working well on GNOME now! :partying_face:

**Comment by 34N0** [comment]
From now on, when looping is disabled in config a timestamp will be displayed. 
#83
