### ISSUE TITLE
[BUG] has no effect on SDDM

### ISSUE THREAD

**Issue by qoijjj** [34N0/pam-authramp#80]
I entered 10 incorrect passwords in a row and then after that could immediately login with the correct password, with no delay.

Expected behavior: I shouldn't have been able to enter 10 incorrect passwords in a row to begin with, without waiting after the 6th incorrect password

**Comment by qoijjj** [comment]
This is with countdown disabled

**Comment by qoijjj** [comment]
this is on any secureblue kinoite image with tag `br-staging-40`

**Comment by 34N0** [comment]
Can you post logs? just look for authramp in journalctl.

**Comment by qoijjj** [comment]
@34N0 

```
libpam_authramp(kde:auth): Os { code: 13, kind: PermissionDenied, message: "Permission denied" }: Error creating tally file:
```

**Comment by 34N0** [comment]
unable to reproduce. rebased to kinoite from silverblue and the lockout worked as expected. was this on a fresh rebase or didi you rebase from a GDM image?

**Comment by 34N0** [comment]
> @34N0
> 
> ```
> libpam_authramp(kde:auth): Os { code: 13, kind: PermissionDenied, message: "Permission denied" }: Error creating tally file:
> ```

Different display managers run with different user privileges which pam inherit. So if you tested authramp with GDM first and then with SDDM this error would make sense!

**Comment by qoijjj** [comment]
@34N0 i tested on SDDM, then GDM, then SDDM. SDDM had the same behavior both times.

I'm not following why the rebase would matter.

Does it matter that my user isn't a member of `wheel`?

**Comment by 34N0** [comment]
hmm if not being part of wheel breaks authramp, then it would have to break faillock too. this would mean there is currently no brute force protection in stable if people follow the postinstall guide?

**Comment by qoijjj** [comment]
@34N0 I wasn't asserting that not being wheel is the issue. I was just throwing it out there.

**Comment by qoijjj** [comment]
@34N0 maybe it's some other group membership though

The tally dir on my system doesn't even exist, so something is breaking:

```
$ ls -l /var/run/authramp
ls: cannot access '/var/run/authramp': No such file or directory
```

I can try using other directories maybe?

**Comment by qoijjj** [comment]
@34N0 I tried with SELinux disabled, and the error still occurred.

I'm trying to rule out as much as possible.


I also see that faillock is successfully creating its dir on my system, so the nonwheel user is probably not the issue:

```
drwxr-xr-x.  2 root           root             40 Jun 27 17:02 faillock
```

What level of privilege is authramp running under when attempting to create the tally dir?

**Comment by qoijjj** [comment]
I just tested with SDDM and looked at the logs. The error from above is missing, so that's fixed now!

And it looks like based on the logs that the logic is working correctly, it says "account getting bounced, account still locked until..."

However, critically, SDDM isn't reflecting the lockout still. It does the "vibration/error" animation, and then shows a working textbox again. And the problem with that aside from being misleading is that if the user then enters the correct password while the account is locked, it appears that authramp is counting that as another failure and therefore it iterates the tally again. This could lead to a potentially permanent lockout where the user can lock themselves out for even longer by entering the correct password more and more.

So it looks like there's two issues left, one in the logic and one that's just for SDDM:

1. correct passwords during account lock count as failures (they should be ignored I think)
2. SDDM doesn't prevent the user from entering passwords during account lock. 

Let me know if you're able to reproduce either or both. The first one is probably more important since it's a logic issue as opposed to an SDDM specific issue.

**Comment by 34N0** [comment]
> * correct passwords during account lock count as failures (they should be ignored I think)

#84

**Comment by RoyalOughtness** [comment]
@34N0 just so I understand the fix, this part is a known SDDM bug right?

> SDDM doesn't prevent the user from entering passwords during account lock.

**Comment by RoyalOughtness** [comment]
as in, this happens with faillock too?

**Comment by wandapeter** [comment]
yes SDD behaviour is locking out the user without any feedback. Users are able to enter passwords but all attempts fail.
